// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: p9_core.proto

package server

import (
	"context"

	"github.com/ns9ryan/p9_core/rpc/internal/logic/roleservice"
	"github.com/ns9ryan/p9_core/rpc/internal/svc"
	"github.com/ns9ryan/p9_core/rpc/pb/core"
	"github.com/ns9ryan/p9_core/rpc/pb/core/role"
)

type RoleServiceServer struct {
	svcCtx *svc.ServiceContext
	core.UnimplementedRoleServiceServer
}

func NewRoleServiceServer(svcCtx *svc.ServiceContext) *RoleServiceServer {
	return &RoleServiceServer{
		svcCtx: svcCtx,
	}
}

// 创建角色
func (s *RoleServiceServer) Create(ctx context.Context, in *role.CreateRoleRequest) (*role.CreateRoleResponse, error) {
	l := roleservicelogic.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}

// 更新角色
func (s *RoleServiceServer) Update(ctx context.Context, in *role.UpdateRoleRequest) (*role.UpdateRoleResponse, error) {
	l := roleservicelogic.NewUpdateLogic(ctx, s.svcCtx)
	return l.Update(in)
}

// 获取角色
func (s *RoleServiceServer) Get(ctx context.Context, in *role.GetRoleRequest) (*role.GetRoleResponse, error) {
	l := roleservicelogic.NewGetLogic(ctx, s.svcCtx)
	return l.Get(in)
}

// 获取角色列表
func (s *RoleServiceServer) List(ctx context.Context, in *role.ListRolesRequest) (*role.ListRolesResponse, error) {
	l := roleservicelogic.NewListLogic(ctx, s.svcCtx)
	return l.List(in)
}

// 批量删除角色
func (s *RoleServiceServer) BatchDelete(ctx context.Context, in *role.BatchDeleteRolesRequest) (*role.BatchDeleteRolesResponse, error) {
	l := roleservicelogic.NewBatchDeleteLogic(ctx, s.svcCtx)
	return l.BatchDelete(in)
}
