// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.32.0
// source: types/role.proto

package role

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 角色信息
type RoleInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 角色 ID
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 展示名称
	Trans string `protobuf:"bytes,2,opt,name=trans,proto3" json:"trans,omitempty"`
	// 状态
	Status uint32 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	// 角色名称
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// 角色编码
	Code string `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	// 备注
	Remark string `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark,omitempty"`
	// 排序
	Sort          uint32 `protobuf:"varint,7,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleInfo) Reset() {
	*x = RoleInfo{}
	mi := &file_types_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleInfo) ProtoMessage() {}

func (x *RoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_types_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleInfo.ProtoReflect.Descriptor instead.
func (*RoleInfo) Descriptor() ([]byte, []int) {
	return file_types_role_proto_rawDescGZIP(), []int{0}
}

func (x *RoleInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleInfo) GetTrans() string {
	if x != nil {
		return x.Trans
	}
	return ""
}

func (x *RoleInfo) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RoleInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RoleInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *RoleInfo) GetSort() uint32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

// 创建角色请求
type CreateRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 状态
	Status *uint32 `protobuf:"varint,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	// 角色名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 角色编码
	Code string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	// 备注
	Remark *string `protobuf:"bytes,4,opt,name=remark,proto3,oneof" json:"remark,omitempty"`
	// 排序
	Sort          *uint32 `protobuf:"varint,5,opt,name=sort,proto3,oneof" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_types_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_types_role_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoleRequest) GetStatus() uint32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateRoleRequest) GetRemark() string {
	if x != nil && x.Remark != nil {
		return *x.Remark
	}
	return ""
}

func (x *CreateRoleRequest) GetSort() uint32 {
	if x != nil && x.Sort != nil {
		return *x.Sort
	}
	return 0
}

// 创建角色响应
type CreateRoleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 角色 ID
	Id            uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleResponse) Reset() {
	*x = CreateRoleResponse{}
	mi := &file_types_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleResponse) ProtoMessage() {}

func (x *CreateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleResponse.ProtoReflect.Descriptor instead.
func (*CreateRoleResponse) Descriptor() ([]byte, []int) {
	return file_types_role_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRoleResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 更新角色请求
type UpdateRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 角色 ID
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 状态
	Status *uint32 `protobuf:"varint,2,opt,name=status,proto3,oneof" json:"status,omitempty"`
	// 角色名称
	Name *string `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// 角色编码
	Code *string `protobuf:"bytes,4,opt,name=code,proto3,oneof" json:"code,omitempty"`
	// 备注
	Remark *string `protobuf:"bytes,5,opt,name=remark,proto3,oneof" json:"remark,omitempty"`
	// 排序
	Sort          *uint32 `protobuf:"varint,6,opt,name=sort,proto3,oneof" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_types_role_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_role_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return file_types_role_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateRoleRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRoleRequest) GetStatus() uint32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *UpdateRoleRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateRoleRequest) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

func (x *UpdateRoleRequest) GetRemark() string {
	if x != nil && x.Remark != nil {
		return *x.Remark
	}
	return ""
}

func (x *UpdateRoleRequest) GetSort() uint32 {
	if x != nil && x.Sort != nil {
		return *x.Sort
	}
	return 0
}

// 更新角色响应
type UpdateRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleResponse) Reset() {
	*x = UpdateRoleResponse{}
	mi := &file_types_role_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleResponse) ProtoMessage() {}

func (x *UpdateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_role_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoleResponse) Descriptor() ([]byte, []int) {
	return file_types_role_proto_rawDescGZIP(), []int{4}
}

// 获取角色请求
type GetRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 角色 ID
	Id            uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleRequest) Reset() {
	*x = GetRoleRequest{}
	mi := &file_types_role_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleRequest) ProtoMessage() {}

func (x *GetRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_role_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleRequest.ProtoReflect.Descriptor instead.
func (*GetRoleRequest) Descriptor() ([]byte, []int) {
	return file_types_role_proto_rawDescGZIP(), []int{5}
}

func (x *GetRoleRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 获取角色响应
type GetRoleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 角色信息
	Role          *RoleInfo `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleResponse) Reset() {
	*x = GetRoleResponse{}
	mi := &file_types_role_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleResponse) ProtoMessage() {}

func (x *GetRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_role_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleResponse.ProtoReflect.Descriptor instead.
func (*GetRoleResponse) Descriptor() ([]byte, []int) {
	return file_types_role_proto_rawDescGZIP(), []int{6}
}

func (x *GetRoleResponse) GetRole() *RoleInfo {
	if x != nil {
		return x.Role
	}
	return nil
}

// 获取角色列表请求
type ListRolesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 页码, 从 1 开始
	Page uint64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// 每页数量
	PageSize uint64 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// 状态
	Status *uint32 `protobuf:"varint,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
	// 角色名称
	Name *string `protobuf:"bytes,4,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// 角色编码
	Code          *string `protobuf:"bytes,5,opt,name=code,proto3,oneof" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesRequest) Reset() {
	*x = ListRolesRequest{}
	mi := &file_types_role_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesRequest) ProtoMessage() {}

func (x *ListRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_role_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesRequest.ProtoReflect.Descriptor instead.
func (*ListRolesRequest) Descriptor() ([]byte, []int) {
	return file_types_role_proto_rawDescGZIP(), []int{7}
}

func (x *ListRolesRequest) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRolesRequest) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRolesRequest) GetStatus() uint32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *ListRolesRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ListRolesRequest) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

// 获取角色列表响应
type ListRolesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 数据总数
	Total uint64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// 角色列表
	Data          []*RoleInfo `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesResponse) Reset() {
	*x = ListRolesResponse{}
	mi := &file_types_role_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesResponse) ProtoMessage() {}

func (x *ListRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_role_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesResponse.ProtoReflect.Descriptor instead.
func (*ListRolesResponse) Descriptor() ([]byte, []int) {
	return file_types_role_proto_rawDescGZIP(), []int{8}
}

func (x *ListRolesResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListRolesResponse) GetData() []*RoleInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// 批量删除角色请求
type BatchDeleteRolesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 角色 ID 列表
	Ids           []uint64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDeleteRolesRequest) Reset() {
	*x = BatchDeleteRolesRequest{}
	mi := &file_types_role_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDeleteRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDeleteRolesRequest) ProtoMessage() {}

func (x *BatchDeleteRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_role_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDeleteRolesRequest.ProtoReflect.Descriptor instead.
func (*BatchDeleteRolesRequest) Descriptor() ([]byte, []int) {
	return file_types_role_proto_rawDescGZIP(), []int{9}
}

func (x *BatchDeleteRolesRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

// 批量删除角色响应
type BatchDeleteRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDeleteRolesResponse) Reset() {
	*x = BatchDeleteRolesResponse{}
	mi := &file_types_role_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDeleteRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDeleteRolesResponse) ProtoMessage() {}

func (x *BatchDeleteRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_role_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDeleteRolesResponse.ProtoReflect.Descriptor instead.
func (*BatchDeleteRolesResponse) Descriptor() ([]byte, []int) {
	return file_types_role_proto_rawDescGZIP(), []int{10}
}

var File_types_role_proto protoreflect.FileDescriptor

const file_types_role_proto_rawDesc = "" +
	"\n" +
	"\x10types/role.proto\x12\x04role\"\x9c\x01\n" +
	"\bRoleInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05trans\x18\x02 \x01(\tR\x05trans\x12\x16\n" +
	"\x06status\x18\x03 \x01(\rR\x06status\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x05 \x01(\tR\x04code\x12\x16\n" +
	"\x06remark\x18\x06 \x01(\tR\x06remark\x12\x12\n" +
	"\x04sort\x18\a \x01(\rR\x04sort\"\xad\x01\n" +
	"\x11CreateRoleRequest\x12\x1b\n" +
	"\x06status\x18\x01 \x01(\rH\x00R\x06status\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x1b\n" +
	"\x06remark\x18\x04 \x01(\tH\x01R\x06remark\x88\x01\x01\x12\x17\n" +
	"\x04sort\x18\x05 \x01(\rH\x02R\x04sort\x88\x01\x01B\t\n" +
	"\a_statusB\t\n" +
	"\a_remarkB\a\n" +
	"\x05_sort\"$\n" +
	"\x12CreateRoleResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xd9\x01\n" +
	"\x11UpdateRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\x06status\x18\x02 \x01(\rH\x00R\x06status\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x01R\x04name\x88\x01\x01\x12\x17\n" +
	"\x04code\x18\x04 \x01(\tH\x02R\x04code\x88\x01\x01\x12\x1b\n" +
	"\x06remark\x18\x05 \x01(\tH\x03R\x06remark\x88\x01\x01\x12\x17\n" +
	"\x04sort\x18\x06 \x01(\rH\x04R\x04sort\x88\x01\x01B\t\n" +
	"\a_statusB\a\n" +
	"\x05_nameB\a\n" +
	"\x05_codeB\t\n" +
	"\a_remarkB\a\n" +
	"\x05_sort\"\x14\n" +
	"\x12UpdateRoleResponse\" \n" +
	"\x0eGetRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"5\n" +
	"\x0fGetRoleResponse\x12\"\n" +
	"\x04role\x18\x01 \x01(\v2\x0e.role.RoleInfoR\x04role\"\xaf\x01\n" +
	"\x10ListRolesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x04R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x04R\bpageSize\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\rH\x00R\x06status\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x04 \x01(\tH\x01R\x04name\x88\x01\x01\x12\x17\n" +
	"\x04code\x18\x05 \x01(\tH\x02R\x04code\x88\x01\x01B\t\n" +
	"\a_statusB\a\n" +
	"\x05_nameB\a\n" +
	"\x05_code\"M\n" +
	"\x11ListRolesResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total\x12\"\n" +
	"\x04data\x18\x02 \x03(\v2\x0e.role.RoleInfoR\x04data\"+\n" +
	"\x17BatchDeleteRolesRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x04R\x03ids\"\x1a\n" +
	"\x18BatchDeleteRolesResponseB-Z+github.com/ns9ryan/p9_core/rpc/pb/core/roleb\x06proto3"

var (
	file_types_role_proto_rawDescOnce sync.Once
	file_types_role_proto_rawDescData []byte
)

func file_types_role_proto_rawDescGZIP() []byte {
	file_types_role_proto_rawDescOnce.Do(func() {
		file_types_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_role_proto_rawDesc), len(file_types_role_proto_rawDesc)))
	})
	return file_types_role_proto_rawDescData
}

var file_types_role_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_types_role_proto_goTypes = []any{
	(*RoleInfo)(nil),                 // 0: role.RoleInfo
	(*CreateRoleRequest)(nil),        // 1: role.CreateRoleRequest
	(*CreateRoleResponse)(nil),       // 2: role.CreateRoleResponse
	(*UpdateRoleRequest)(nil),        // 3: role.UpdateRoleRequest
	(*UpdateRoleResponse)(nil),       // 4: role.UpdateRoleResponse
	(*GetRoleRequest)(nil),           // 5: role.GetRoleRequest
	(*GetRoleResponse)(nil),          // 6: role.GetRoleResponse
	(*ListRolesRequest)(nil),         // 7: role.ListRolesRequest
	(*ListRolesResponse)(nil),        // 8: role.ListRolesResponse
	(*BatchDeleteRolesRequest)(nil),  // 9: role.BatchDeleteRolesRequest
	(*BatchDeleteRolesResponse)(nil), // 10: role.BatchDeleteRolesResponse
}
var file_types_role_proto_depIdxs = []int32{
	0, // 0: role.GetRoleResponse.role:type_name -> role.RoleInfo
	0, // 1: role.ListRolesResponse.data:type_name -> role.RoleInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_types_role_proto_init() }
func file_types_role_proto_init() {
	if File_types_role_proto != nil {
		return
	}
	file_types_role_proto_msgTypes[1].OneofWrappers = []any{}
	file_types_role_proto_msgTypes[3].OneofWrappers = []any{}
	file_types_role_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_role_proto_rawDesc), len(file_types_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_role_proto_goTypes,
		DependencyIndexes: file_types_role_proto_depIdxs,
		MessageInfos:      file_types_role_proto_msgTypes,
	}.Build()
	File_types_role_proto = out.File
	file_types_role_proto_goTypes = nil
	file_types_role_proto_depIdxs = nil
}
