// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: p9_core.proto

package baseservice

import (
	"context"

	"github.com/ns9ryan/p9_core/rpc/pb/core"

	"github.com/ns9ryan/p9_core/rpc/pb/core/base"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BaseService interface {
		// 初始化数据库
		InitDatabase(ctx context.Context, in *base.InitDatabaseRequest, opts ...grpc.CallOption) (*base.InitDatabaseResponse, error)
	}

	defaultBaseService struct {
		cli zrpc.Client
	}
)

func NewBaseService(cli zrpc.Client) BaseService {
	return &defaultBaseService{
		cli: cli,
	}
}

// 初始化数据库
func (m *defaultBaseService) InitDatabase(ctx context.Context, in *base.InitDatabaseRequest, opts ...grpc.CallOption) (*base.InitDatabaseResponse, error) {
	client := core.NewBaseServiceClient(m.cli.Conn())
	return client.InitDatabase(ctx, in, opts...)
}
