// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	base "github.com/ns9ryan/p9_core/api/internal/handler/base"
	ping "github.com/ns9ryan/p9_core/api/internal/handler/ping"
	role "github.com/ns9ryan/p9_core/api/internal/handler/role"
	"github.com/ns9ryan/p9_core/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/core/init/database",
				Handler: base.InitDatabaseHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: ping.PingHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/role",
				Handler: role.GetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/role/create",
				Handler: role.CreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/role/delete",
				Handler: role.DeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/role/list",
				Handler: role.ListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/role/update",
				Handler: role.UpdateHandler(serverCtx),
			},
		},
	)
}
