// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ns9ryan/p9_core/rpc/ent/dictionary"
	"github.com/ns9ryan/p9_core/rpc/ent/predicate"
)

// DictionaryUpdate is the builder for updating Dictionary entities.
type DictionaryUpdate struct {
	config
	hooks    []Hook
	mutation *DictionaryMutation
}

// Where appends a list predicates to the DictionaryUpdate builder.
func (_u *DictionaryUpdate) Where(ps ...predicate.Dictionary) *DictionaryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DictionaryUpdate) SetUpdatedAt(v time.Time) *DictionaryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *DictionaryUpdate) SetStatus(v uint8) *DictionaryUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DictionaryUpdate) SetNillableStatus(v *uint8) *DictionaryUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *DictionaryUpdate) AddStatus(v int8) *DictionaryUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *DictionaryUpdate) ClearStatus() *DictionaryUpdate {
	_u.mutation.ClearStatus()
	return _u
}

// SetTitle sets the "title" field.
func (_u *DictionaryUpdate) SetTitle(v string) *DictionaryUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *DictionaryUpdate) SetNillableTitle(v *string) *DictionaryUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *DictionaryUpdate) SetName(v string) *DictionaryUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DictionaryUpdate) SetNillableName(v *string) *DictionaryUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDesc sets the "desc" field.
func (_u *DictionaryUpdate) SetDesc(v string) *DictionaryUpdate {
	_u.mutation.SetDesc(v)
	return _u
}

// SetNillableDesc sets the "desc" field if the given value is not nil.
func (_u *DictionaryUpdate) SetNillableDesc(v *string) *DictionaryUpdate {
	if v != nil {
		_u.SetDesc(*v)
	}
	return _u
}

// ClearDesc clears the value of the "desc" field.
func (_u *DictionaryUpdate) ClearDesc() *DictionaryUpdate {
	_u.mutation.ClearDesc()
	return _u
}

// SetIsPublic sets the "is_public" field.
func (_u *DictionaryUpdate) SetIsPublic(v bool) *DictionaryUpdate {
	_u.mutation.SetIsPublic(v)
	return _u
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_u *DictionaryUpdate) SetNillableIsPublic(v *bool) *DictionaryUpdate {
	if v != nil {
		_u.SetIsPublic(*v)
	}
	return _u
}

// Mutation returns the DictionaryMutation object of the builder.
func (_u *DictionaryUpdate) Mutation() *DictionaryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DictionaryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DictionaryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DictionaryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DictionaryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DictionaryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dictionary.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *DictionaryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(dictionary.Table, dictionary.Columns, sqlgraph.NewFieldSpec(dictionary.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dictionary.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(dictionary.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(dictionary.FieldStatus, field.TypeUint8, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(dictionary.FieldStatus, field.TypeUint8)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(dictionary.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(dictionary.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Desc(); ok {
		_spec.SetField(dictionary.FieldDesc, field.TypeString, value)
	}
	if _u.mutation.DescCleared() {
		_spec.ClearField(dictionary.FieldDesc, field.TypeString)
	}
	if value, ok := _u.mutation.IsPublic(); ok {
		_spec.SetField(dictionary.FieldIsPublic, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dictionary.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DictionaryUpdateOne is the builder for updating a single Dictionary entity.
type DictionaryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DictionaryMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DictionaryUpdateOne) SetUpdatedAt(v time.Time) *DictionaryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *DictionaryUpdateOne) SetStatus(v uint8) *DictionaryUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DictionaryUpdateOne) SetNillableStatus(v *uint8) *DictionaryUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *DictionaryUpdateOne) AddStatus(v int8) *DictionaryUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *DictionaryUpdateOne) ClearStatus() *DictionaryUpdateOne {
	_u.mutation.ClearStatus()
	return _u
}

// SetTitle sets the "title" field.
func (_u *DictionaryUpdateOne) SetTitle(v string) *DictionaryUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *DictionaryUpdateOne) SetNillableTitle(v *string) *DictionaryUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *DictionaryUpdateOne) SetName(v string) *DictionaryUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DictionaryUpdateOne) SetNillableName(v *string) *DictionaryUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDesc sets the "desc" field.
func (_u *DictionaryUpdateOne) SetDesc(v string) *DictionaryUpdateOne {
	_u.mutation.SetDesc(v)
	return _u
}

// SetNillableDesc sets the "desc" field if the given value is not nil.
func (_u *DictionaryUpdateOne) SetNillableDesc(v *string) *DictionaryUpdateOne {
	if v != nil {
		_u.SetDesc(*v)
	}
	return _u
}

// ClearDesc clears the value of the "desc" field.
func (_u *DictionaryUpdateOne) ClearDesc() *DictionaryUpdateOne {
	_u.mutation.ClearDesc()
	return _u
}

// SetIsPublic sets the "is_public" field.
func (_u *DictionaryUpdateOne) SetIsPublic(v bool) *DictionaryUpdateOne {
	_u.mutation.SetIsPublic(v)
	return _u
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_u *DictionaryUpdateOne) SetNillableIsPublic(v *bool) *DictionaryUpdateOne {
	if v != nil {
		_u.SetIsPublic(*v)
	}
	return _u
}

// Mutation returns the DictionaryMutation object of the builder.
func (_u *DictionaryUpdateOne) Mutation() *DictionaryMutation {
	return _u.mutation
}

// Where appends a list predicates to the DictionaryUpdate builder.
func (_u *DictionaryUpdateOne) Where(ps ...predicate.Dictionary) *DictionaryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DictionaryUpdateOne) Select(field string, fields ...string) *DictionaryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Dictionary entity.
func (_u *DictionaryUpdateOne) Save(ctx context.Context) (*Dictionary, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DictionaryUpdateOne) SaveX(ctx context.Context) *Dictionary {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DictionaryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DictionaryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DictionaryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dictionary.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *DictionaryUpdateOne) sqlSave(ctx context.Context) (_node *Dictionary, err error) {
	_spec := sqlgraph.NewUpdateSpec(dictionary.Table, dictionary.Columns, sqlgraph.NewFieldSpec(dictionary.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Dictionary.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dictionary.FieldID)
		for _, f := range fields {
			if !dictionary.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dictionary.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dictionary.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(dictionary.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(dictionary.FieldStatus, field.TypeUint8, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(dictionary.FieldStatus, field.TypeUint8)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(dictionary.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(dictionary.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Desc(); ok {
		_spec.SetField(dictionary.FieldDesc, field.TypeString, value)
	}
	if _u.mutation.DescCleared() {
		_spec.ClearField(dictionary.FieldDesc, field.TypeString)
	}
	if value, ok := _u.mutation.IsPublic(); ok {
		_spec.SetField(dictionary.FieldIsPublic, field.TypeBool, value)
	}
	_node = &Dictionary{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dictionary.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
