// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/ns9ryan/p9_core/rpc/ent/api"
	"github.com/ns9ryan/p9_core/rpc/ent/configuration"
	"github.com/ns9ryan/p9_core/rpc/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	apiMixin := schema.API{}.Mixin()
	apiMixinFields0 := apiMixin[0].Fields()
	_ = apiMixinFields0
	apiFields := schema.API{}.Fields()
	_ = apiFields
	// apiDescCreatedAt is the schema descriptor for created_at field.
	apiDescCreatedAt := apiMixinFields0[1].Descriptor()
	// api.DefaultCreatedAt holds the default value on creation for the created_at field.
	api.DefaultCreatedAt = apiDescCreatedAt.Default.(func() time.Time)
	// apiDescUpdatedAt is the schema descriptor for updated_at field.
	apiDescUpdatedAt := apiMixinFields0[2].Descriptor()
	// api.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	api.DefaultUpdatedAt = apiDescUpdatedAt.Default.(func() time.Time)
	// api.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	api.UpdateDefaultUpdatedAt = apiDescUpdatedAt.UpdateDefault.(func() time.Time)
	// apiDescMethod is the schema descriptor for method field.
	apiDescMethod := apiFields[1].Descriptor()
	// api.DefaultMethod holds the default value on creation for the method field.
	api.DefaultMethod = apiDescMethod.Default.(string)
	// apiDescServiceName is the schema descriptor for service_name field.
	apiDescServiceName := apiFields[4].Descriptor()
	// api.DefaultServiceName holds the default value on creation for the service_name field.
	api.DefaultServiceName = apiDescServiceName.Default.(string)
	// apiDescIsRequired is the schema descriptor for is_required field.
	apiDescIsRequired := apiFields[5].Descriptor()
	// api.DefaultIsRequired holds the default value on creation for the is_required field.
	api.DefaultIsRequired = apiDescIsRequired.Default.(bool)
	configurationMixin := schema.Configuration{}.Mixin()
	configurationMixinFields0 := configurationMixin[0].Fields()
	_ = configurationMixinFields0
	configurationMixinFields1 := configurationMixin[1].Fields()
	_ = configurationMixinFields1
	configurationMixinFields2 := configurationMixin[2].Fields()
	_ = configurationMixinFields2
	configurationFields := schema.Configuration{}.Fields()
	_ = configurationFields
	// configurationDescCreatedAt is the schema descriptor for created_at field.
	configurationDescCreatedAt := configurationMixinFields0[1].Descriptor()
	// configuration.DefaultCreatedAt holds the default value on creation for the created_at field.
	configuration.DefaultCreatedAt = configurationDescCreatedAt.Default.(func() time.Time)
	// configurationDescUpdatedAt is the schema descriptor for updated_at field.
	configurationDescUpdatedAt := configurationMixinFields0[2].Descriptor()
	// configuration.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	configuration.DefaultUpdatedAt = configurationDescUpdatedAt.Default.(func() time.Time)
	// configuration.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	configuration.UpdateDefaultUpdatedAt = configurationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// configurationDescSort is the schema descriptor for sort field.
	configurationDescSort := configurationMixinFields1[0].Descriptor()
	// configuration.DefaultSort holds the default value on creation for the sort field.
	configuration.DefaultSort = configurationDescSort.Default.(uint32)
	// configurationDescState is the schema descriptor for state field.
	configurationDescState := configurationMixinFields2[0].Descriptor()
	// configuration.DefaultState holds the default value on creation for the state field.
	configuration.DefaultState = configurationDescState.Default.(bool)
}
