// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SysApisColumns holds the columns for the "sys_apis" table.
	SysApisColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true, Comment: "主键 ID"},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "更新时间"},
		{Name: "path", Type: field.TypeString, Comment: "API 路径"},
		{Name: "method", Type: field.TypeString, Comment: "HTTP 请求方法", Default: "POST"},
		{Name: "description", Type: field.TypeString, Comment: "API 描述"},
		{Name: "api_group", Type: field.TypeString, Comment: "API 分组"},
		{Name: "service_name", Type: field.TypeString, Comment: "服务名称", Default: "Other"},
		{Name: "is_required", Type: field.TypeBool, Comment: "是否为必要接口", Default: false},
	}
	// SysApisTable holds the schema information for the "sys_apis" table.
	SysApisTable = &schema.Table{
		Name:       "sys_apis",
		Comment:    "API 接口表",
		Columns:    SysApisColumns,
		PrimaryKey: []*schema.Column{SysApisColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "api_path_method",
				Unique:  true,
				Columns: []*schema.Column{SysApisColumns[3], SysApisColumns[4]},
			},
		},
	}
	// SysConfigurationColumns holds the columns for the "sys_configuration" table.
	SysConfigurationColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true, Comment: "主键 ID"},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "更新时间"},
		{Name: "sort", Type: field.TypeUint32, Comment: "排序编号", Default: 1},
		{Name: "state", Type: field.TypeBool, Nullable: true, Comment: "状态：true 正常，false 禁用", Default: true},
		{Name: "name", Type: field.TypeString, Comment: "配置名称"},
		{Name: "key", Type: field.TypeString, Comment: "配置键名"},
		{Name: "value", Type: field.TypeString, Comment: "配置值"},
		{Name: "category", Type: field.TypeString, Comment: "配置分类"},
		{Name: "remark", Type: field.TypeString, Nullable: true, Comment: "备注"},
	}
	// SysConfigurationTable holds the schema information for the "sys_configuration" table.
	SysConfigurationTable = &schema.Table{
		Name:       "sys_configuration",
		Comment:    "动态配置表",
		Columns:    SysConfigurationColumns,
		PrimaryKey: []*schema.Column{SysConfigurationColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "configuration_key",
				Unique:  false,
				Columns: []*schema.Column{SysConfigurationColumns[6]},
			},
		},
	}
	// SysDepartmentsColumns holds the columns for the "sys_departments" table.
	SysDepartmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true, Comment: "主键 ID"},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "更新时间"},
		{Name: "status", Type: field.TypeUint32, Comment: "状态：1 正常，2 停用", Default: 1, SchemaType: map[string]string{"postgres": "smallint"}},
		{Name: "sort", Type: field.TypeUint32, Comment: "排序编号", Default: 1},
		{Name: "name", Type: field.TypeString, Comment: "部门名称"},
		{Name: "ancestors", Type: field.TypeString, Nullable: true, Comment: "父级部门列表"},
		{Name: "leader", Type: field.TypeString, Nullable: true, Comment: "部门负责人"},
		{Name: "phone", Type: field.TypeString, Nullable: true, Comment: "负责人电话"},
		{Name: "email", Type: field.TypeString, Nullable: true, Comment: "负责人邮箱"},
		{Name: "remark", Type: field.TypeString, Nullable: true, Comment: "备注"},
		{Name: "parent_id", Type: field.TypeUint64, Nullable: true, Comment: "父级部门 ID", Default: 0},
	}
	// SysDepartmentsTable holds the schema information for the "sys_departments" table.
	SysDepartmentsTable = &schema.Table{
		Name:       "sys_departments",
		Comment:    "部门表",
		Columns:    SysDepartmentsColumns,
		PrimaryKey: []*schema.Column{SysDepartmentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_departments_sys_departments_children",
				Columns:    []*schema.Column{SysDepartmentsColumns[11]},
				RefColumns: []*schema.Column{SysDepartmentsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// SysDictionariesColumns holds the columns for the "sys_dictionaries" table.
	SysDictionariesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true, Comment: "主键 ID"},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "更新时间"},
		{Name: "status", Type: field.TypeUint32, Comment: "状态：1 正常，2 停用", Default: 1, SchemaType: map[string]string{"postgres": "smallint"}},
		{Name: "title", Type: field.TypeString, Comment: "展示名称"},
		{Name: "name", Type: field.TypeString, Unique: true, Comment: "字典名称"},
		{Name: "desc", Type: field.TypeString, Nullable: true, Comment: "字典描述"},
		{Name: "is_public", Type: field.TypeBool, Comment: "是否公开，无需登录即可访问", Default: false},
	}
	// SysDictionariesTable holds the schema information for the "sys_dictionaries" table.
	SysDictionariesTable = &schema.Table{
		Name:       "sys_dictionaries",
		Comment:    "字典信息表",
		Columns:    SysDictionariesColumns,
		PrimaryKey: []*schema.Column{SysDictionariesColumns[0]},
	}
	// SysDictionaryDetailsColumns holds the columns for the "sys_dictionary_details" table.
	SysDictionaryDetailsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true, Comment: "主键 ID"},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "更新时间"},
		{Name: "status", Type: field.TypeUint32, Comment: "状态：1 正常，2 停用", Default: 1, SchemaType: map[string]string{"postgres": "smallint"}},
		{Name: "sort", Type: field.TypeUint32, Comment: "排序编号", Default: 1},
		{Name: "title", Type: field.TypeString, Comment: "展示名称"},
		{Name: "key", Type: field.TypeString, Comment: "键"},
		{Name: "value", Type: field.TypeString, Comment: "值"},
		{Name: "dictionary_id", Type: field.TypeUint64, Nullable: true, Comment: "字典 ID"},
	}
	// SysDictionaryDetailsTable holds the schema information for the "sys_dictionary_details" table.
	SysDictionaryDetailsTable = &schema.Table{
		Name:       "sys_dictionary_details",
		Comment:    "字典键值表",
		Columns:    SysDictionaryDetailsColumns,
		PrimaryKey: []*schema.Column{SysDictionaryDetailsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_dictionary_details_sys_dictionaries_dictionary_details",
				Columns:    []*schema.Column{SysDictionaryDetailsColumns[8]},
				RefColumns: []*schema.Column{SysDictionariesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// LanguagesColumns holds the columns for the "languages" table.
	LanguagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// LanguagesTable holds the schema information for the "languages" table.
	LanguagesTable = &schema.Table{
		Name:       "languages",
		Columns:    LanguagesColumns,
		PrimaryKey: []*schema.Column{LanguagesColumns[0]},
	}
	// SysMenusColumns holds the columns for the "sys_menus" table.
	SysMenusColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true, Comment: "主键 ID"},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "更新时间"},
		{Name: "sort", Type: field.TypeUint32, Comment: "排序编号", Default: 1},
		{Name: "name", Type: field.TypeString, Comment: "菜单名称"},
		{Name: "menu_type", Type: field.TypeUint32, Comment: "菜单类型：0 目录，1 菜单"},
		{Name: "menu_level", Type: field.TypeUint32, Comment: "菜单层级"},
		{Name: "path", Type: field.TypeString, Nullable: true, Comment: "菜单路由路径", Default: ""},
		{Name: "component", Type: field.TypeString, Nullable: true, Comment: "组件路径", Default: ""},
		{Name: "redirect", Type: field.TypeString, Nullable: true, Comment: "跳转路径", Default: ""},
		{Name: "service_name", Type: field.TypeString, Nullable: true, Comment: "服务名称", Default: "Other"},
		{Name: "permission", Type: field.TypeString, Nullable: true, Comment: "权限标识"},
		{Name: "disabled", Type: field.TypeBool, Nullable: true, Comment: "是否停用", Default: false},
		{Name: "title", Type: field.TypeString, Comment: "菜单显示标题"},
		{Name: "icon", Type: field.TypeString, Comment: "菜单图标"},
		{Name: "hide_menu", Type: field.TypeBool, Nullable: true, Comment: "是否隐藏菜单", Default: false},
		{Name: "hide_breadcrumb", Type: field.TypeBool, Nullable: true, Comment: "是否隐藏面包屑", Default: false},
		{Name: "ignore_keep_alive", Type: field.TypeBool, Nullable: true, Comment: "是否取消页面缓存", Default: false},
		{Name: "hide_tab", Type: field.TypeBool, Nullable: true, Comment: "是否隐藏页签", Default: false},
		{Name: "frame_src", Type: field.TypeString, Nullable: true, Comment: "内嵌页面地址", Default: ""},
		{Name: "carry_param", Type: field.TypeBool, Nullable: true, Comment: "是否携带路由参数", Default: false},
		{Name: "hide_children_in_menu", Type: field.TypeBool, Nullable: true, Comment: "是否隐藏子菜单", Default: false},
		{Name: "affix", Type: field.TypeBool, Nullable: true, Comment: "是否固定页签", Default: false},
		{Name: "dynamic_level", Type: field.TypeUint32, Nullable: true, Comment: "最大可打开子页签数量", Default: 20},
		{Name: "real_path", Type: field.TypeString, Nullable: true, Comment: "不包含动态参数的实际路由路径", Default: ""},
		{Name: "parent_id", Type: field.TypeUint64, Nullable: true, Comment: "父菜单 ID", Default: 100000},
	}
	// SysMenusTable holds the schema information for the "sys_menus" table.
	SysMenusTable = &schema.Table{
		Name:       "sys_menus",
		Comment:    "菜单表",
		Columns:    SysMenusColumns,
		PrimaryKey: []*schema.Column{SysMenusColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_menus_sys_menus_children",
				Columns:    []*schema.Column{SysMenusColumns[25]},
				RefColumns: []*schema.Column{SysMenusColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "menu_name",
				Unique:  true,
				Columns: []*schema.Column{SysMenusColumns[4]},
			},
			{
				Name:    "menu_path",
				Unique:  true,
				Columns: []*schema.Column{SysMenusColumns[7]},
			},
		},
	}
	// SysOauthProvidersColumns holds the columns for the "sys_oauth_providers" table.
	SysOauthProvidersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true, Comment: "主键 ID"},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "更新时间"},
		{Name: "name", Type: field.TypeString, Unique: true, Comment: "提供商名称"},
		{Name: "client_id", Type: field.TypeString, Comment: "客户端 ID"},
		{Name: "client_secret", Type: field.TypeString, Comment: "客户端密钥"},
		{Name: "redirect_url", Type: field.TypeString, Comment: "回调地址"},
		{Name: "scopes", Type: field.TypeString, Comment: "权限范围"},
		{Name: "auth_url", Type: field.TypeString, Comment: "认证地址"},
		{Name: "token_url", Type: field.TypeString, Comment: "Token 获取地址"},
		{Name: "auth_style", Type: field.TypeUint64, Comment: "鉴权方式：0 自动，1 第三方登录，2 用户名密码登录"},
		{Name: "info_url", Type: field.TypeString, Comment: "用户信息请求地址"},
	}
	// SysOauthProvidersTable holds the schema information for the "sys_oauth_providers" table.
	SysOauthProvidersTable = &schema.Table{
		Name:       "sys_oauth_providers",
		Comment:    "第三方登录配置表",
		Columns:    SysOauthProvidersColumns,
		PrimaryKey: []*schema.Column{SysOauthProvidersColumns[0]},
	}
	// SysPositionsColumns holds the columns for the "sys_positions" table.
	SysPositionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true, Comment: "主键 ID"},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "更新时间"},
		{Name: "status", Type: field.TypeUint32, Comment: "状态：1 正常，2 停用", Default: 1, SchemaType: map[string]string{"postgres": "smallint"}},
		{Name: "sort", Type: field.TypeUint32, Comment: "排序编号", Default: 1},
		{Name: "name", Type: field.TypeString, Comment: "职位名称"},
		{Name: "code", Type: field.TypeString, Comment: "职位编码"},
		{Name: "remark", Type: field.TypeString, Nullable: true, Comment: "备注"},
	}
	// SysPositionsTable holds the schema information for the "sys_positions" table.
	SysPositionsTable = &schema.Table{
		Name:       "sys_positions",
		Comment:    "职位信息表",
		Columns:    SysPositionsColumns,
		PrimaryKey: []*schema.Column{SysPositionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "position_code",
				Unique:  true,
				Columns: []*schema.Column{SysPositionsColumns[6]},
			},
		},
	}
	// SysRolesColumns holds the columns for the "sys_roles" table.
	SysRolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true, Comment: "主键 ID"},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "更新时间"},
		{Name: "status", Type: field.TypeUint32, Comment: "状态：1 正常，2 停用", Default: 1, SchemaType: map[string]string{"postgres": "smallint"}},
		{Name: "sort", Type: field.TypeUint32, Comment: "排序编号", Default: 1},
		{Name: "name", Type: field.TypeString, Comment: "角色名称"},
		{Name: "code", Type: field.TypeString, Comment: "角色编码"},
		{Name: "remark", Type: field.TypeString, Comment: "备注", Default: ""},
	}
	// SysRolesTable holds the schema information for the "sys_roles" table.
	SysRolesTable = &schema.Table{
		Name:       "sys_roles",
		Comment:    "角色信息表",
		Columns:    SysRolesColumns,
		PrimaryKey: []*schema.Column{SysRolesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "role_code",
				Unique:  true,
				Columns: []*schema.Column{SysRolesColumns[6]},
			},
		},
	}
	// SysTokensColumns holds the columns for the "sys_tokens" table.
	SysTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Comment: "UUID 主键"},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "更新时间"},
		{Name: "status", Type: field.TypeUint32, Comment: "状态：1 正常，2 停用", Default: 1, SchemaType: map[string]string{"postgres": "smallint"}},
		{Name: "uuid", Type: field.TypeUUID, Comment: "用户 UUID"},
		{Name: "username", Type: field.TypeString, Comment: "用户名", Default: "unknown"},
		{Name: "token", Type: field.TypeString, Comment: "Token 字符串"},
		{Name: "source", Type: field.TypeString, Comment: "Token 来源"},
		{Name: "expired_at", Type: field.TypeTime, Comment: "过期时间"},
	}
	// SysTokensTable holds the schema information for the "sys_tokens" table.
	SysTokensTable = &schema.Table{
		Name:       "sys_tokens",
		Comment:    "令牌信息表",
		Columns:    SysTokensColumns,
		PrimaryKey: []*schema.Column{SysTokensColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "token_uuid",
				Unique:  false,
				Columns: []*schema.Column{SysTokensColumns[4]},
			},
			{
				Name:    "token_expired_at",
				Unique:  false,
				Columns: []*schema.Column{SysTokensColumns[8]},
			},
		},
	}
	// SysUsersColumns holds the columns for the "sys_users" table.
	SysUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Comment: "UUID 主键"},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "更新时间"},
		{Name: "status", Type: field.TypeUint32, Comment: "状态：1 正常，2 停用", Default: 1, SchemaType: map[string]string{"postgres": "smallint"}},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "username", Type: field.TypeString, Unique: true, Comment: "登录名"},
		{Name: "password", Type: field.TypeString, Comment: "密码"},
		{Name: "nickname", Type: field.TypeString, Unique: true, Comment: "昵称"},
		{Name: "description", Type: field.TypeString, Nullable: true, Comment: "用户描述"},
		{Name: "home_path", Type: field.TypeString, Comment: "登录后首页路径", Default: "/dashboard"},
		{Name: "mobile", Type: field.TypeString, Nullable: true, Comment: "手机号"},
		{Name: "email", Type: field.TypeString, Nullable: true, Comment: "邮箱"},
		{Name: "avatar", Type: field.TypeString, Nullable: true, Comment: "头像路径", SchemaType: map[string]string{"mysql": "varchar(512)"}},
		{Name: "expired_at", Type: field.TypeTime, Nullable: true, Comment: "到期时间", SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "department_id", Type: field.TypeUint64, Nullable: true, Comment: "部门 ID", Default: 1},
	}
	// SysUsersTable holds the schema information for the "sys_users" table.
	SysUsersTable = &schema.Table{
		Name:       "sys_users",
		Comment:    "用户信息表",
		Columns:    SysUsersColumns,
		PrimaryKey: []*schema.Column{SysUsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_users_sys_departments_departments",
				Columns:    []*schema.Column{SysUsersColumns[14]},
				RefColumns: []*schema.Column{SysDepartmentsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "user_username_email",
				Unique:  true,
				Columns: []*schema.Column{SysUsersColumns[5], SysUsersColumns[11]},
			},
		},
	}
	// RoleMenusColumns holds the columns for the "role_menus" table.
	RoleMenusColumns = []*schema.Column{
		{Name: "role_id", Type: field.TypeUint64},
		{Name: "menu_id", Type: field.TypeUint64},
	}
	// RoleMenusTable holds the schema information for the "role_menus" table.
	RoleMenusTable = &schema.Table{
		Name:       "role_menus",
		Columns:    RoleMenusColumns,
		PrimaryKey: []*schema.Column{RoleMenusColumns[0], RoleMenusColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "role_menus_role_id",
				Columns:    []*schema.Column{RoleMenusColumns[0]},
				RefColumns: []*schema.Column{SysRolesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "role_menus_menu_id",
				Columns:    []*schema.Column{RoleMenusColumns[1]},
				RefColumns: []*schema.Column{SysMenusColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// UserPositionsColumns holds the columns for the "user_positions" table.
	UserPositionsColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "position_id", Type: field.TypeUint64},
	}
	// UserPositionsTable holds the schema information for the "user_positions" table.
	UserPositionsTable = &schema.Table{
		Name:       "user_positions",
		Columns:    UserPositionsColumns,
		PrimaryKey: []*schema.Column{UserPositionsColumns[0], UserPositionsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_positions_user_id",
				Columns:    []*schema.Column{UserPositionsColumns[0]},
				RefColumns: []*schema.Column{SysUsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_positions_position_id",
				Columns:    []*schema.Column{UserPositionsColumns[1]},
				RefColumns: []*schema.Column{SysPositionsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// UserRolesColumns holds the columns for the "user_roles" table.
	UserRolesColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "role_id", Type: field.TypeUint64},
	}
	// UserRolesTable holds the schema information for the "user_roles" table.
	UserRolesTable = &schema.Table{
		Name:       "user_roles",
		Columns:    UserRolesColumns,
		PrimaryKey: []*schema.Column{UserRolesColumns[0], UserRolesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_roles_user_id",
				Columns:    []*schema.Column{UserRolesColumns[0]},
				RefColumns: []*schema.Column{SysUsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_roles_role_id",
				Columns:    []*schema.Column{UserRolesColumns[1]},
				RefColumns: []*schema.Column{SysRolesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SysApisTable,
		SysConfigurationTable,
		SysDepartmentsTable,
		SysDictionariesTable,
		SysDictionaryDetailsTable,
		LanguagesTable,
		SysMenusTable,
		SysOauthProvidersTable,
		SysPositionsTable,
		SysRolesTable,
		SysTokensTable,
		SysUsersTable,
		RoleMenusTable,
		UserPositionsTable,
		UserRolesTable,
	}
)

func init() {
	SysApisTable.Annotation = &entsql.Annotation{
		Table: "sys_apis",
	}
	SysConfigurationTable.Annotation = &entsql.Annotation{
		Table: "sys_configuration",
	}
	SysDepartmentsTable.ForeignKeys[0].RefTable = SysDepartmentsTable
	SysDepartmentsTable.Annotation = &entsql.Annotation{
		Table: "sys_departments",
	}
	SysDictionariesTable.Annotation = &entsql.Annotation{
		Table: "sys_dictionaries",
	}
	SysDictionaryDetailsTable.ForeignKeys[0].RefTable = SysDictionariesTable
	SysDictionaryDetailsTable.Annotation = &entsql.Annotation{
		Table: "sys_dictionary_details",
	}
	SysMenusTable.ForeignKeys[0].RefTable = SysMenusTable
	SysMenusTable.Annotation = &entsql.Annotation{
		Table: "sys_menus",
	}
	SysOauthProvidersTable.Annotation = &entsql.Annotation{
		Table: "sys_oauth_providers",
	}
	SysPositionsTable.Annotation = &entsql.Annotation{
		Table: "sys_positions",
	}
	SysRolesTable.Annotation = &entsql.Annotation{
		Table: "sys_roles",
	}
	SysTokensTable.Annotation = &entsql.Annotation{
		Table: "sys_tokens",
	}
	SysUsersTable.ForeignKeys[0].RefTable = SysDepartmentsTable
	SysUsersTable.Annotation = &entsql.Annotation{
		Table: "sys_users",
	}
	RoleMenusTable.ForeignKeys[0].RefTable = SysRolesTable
	RoleMenusTable.ForeignKeys[1].RefTable = SysMenusTable
	UserPositionsTable.ForeignKeys[0].RefTable = SysUsersTable
	UserPositionsTable.ForeignKeys[1].RefTable = SysPositionsTable
	UserRolesTable.ForeignKeys[0].RefTable = SysUsersTable
	UserRolesTable.ForeignKeys[1].RefTable = SysRolesTable
}
