// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SysApisColumns holds the columns for the "sys_apis" table.
	SysApisColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true, Comment: "主键 ID"},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "更新时间"},
		{Name: "path", Type: field.TypeString, Comment: "API 路径"},
		{Name: "method", Type: field.TypeString, Comment: "HTTP 请求方法", Default: "POST"},
		{Name: "description", Type: field.TypeString, Comment: "API 描述"},
		{Name: "api_group", Type: field.TypeString, Comment: "API 分组"},
		{Name: "service_name", Type: field.TypeString, Comment: "服务名称", Default: "Other"},
		{Name: "is_required", Type: field.TypeBool, Comment: "是否为必要接口", Default: false},
	}
	// SysApisTable holds the schema information for the "sys_apis" table.
	SysApisTable = &schema.Table{
		Name:       "sys_apis",
		Comment:    "API 接口表",
		Columns:    SysApisColumns,
		PrimaryKey: []*schema.Column{SysApisColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "api_path_method",
				Unique:  true,
				Columns: []*schema.Column{SysApisColumns[3], SysApisColumns[4]},
			},
		},
	}
	// SysConfigurationColumns holds the columns for the "sys_configuration" table.
	SysConfigurationColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true, Comment: "主键 ID"},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "更新时间"},
		{Name: "sort", Type: field.TypeUint32, Comment: "排序编号", Default: 1},
		{Name: "state", Type: field.TypeBool, Nullable: true, Comment: "状态：true 正常，false 禁用", Default: true},
		{Name: "name", Type: field.TypeString, Comment: "配置名称"},
		{Name: "key", Type: field.TypeString, Comment: "配置键名"},
		{Name: "value", Type: field.TypeString, Comment: "配置值"},
		{Name: "category", Type: field.TypeString, Comment: "配置分类"},
		{Name: "remark", Type: field.TypeString, Nullable: true, Comment: "备注"},
	}
	// SysConfigurationTable holds the schema information for the "sys_configuration" table.
	SysConfigurationTable = &schema.Table{
		Name:       "sys_configuration",
		Comment:    "动态配置表",
		Columns:    SysConfigurationColumns,
		PrimaryKey: []*schema.Column{SysConfigurationColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "configuration_key",
				Unique:  false,
				Columns: []*schema.Column{SysConfigurationColumns[6]},
			},
		},
	}
	// LanguagesColumns holds the columns for the "languages" table.
	LanguagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// LanguagesTable holds the schema information for the "languages" table.
	LanguagesTable = &schema.Table{
		Name:       "languages",
		Columns:    LanguagesColumns,
		PrimaryKey: []*schema.Column{LanguagesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SysApisTable,
		SysConfigurationTable,
		LanguagesTable,
	}
)

func init() {
	SysApisTable.Annotation = &entsql.Annotation{
		Table: "sys_apis",
	}
	SysConfigurationTable.Annotation = &entsql.Annotation{
		Table: "sys_configuration",
	}
}
