// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// API is the predicate function for api builders.
type API func(*sql.Selector)

// Configuration is the predicate function for configuration builders.
type Configuration func(*sql.Selector)

// Language is the predicate function for language builders.
type Language func(*sql.Selector)
