// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: p9_core.proto

package server

import (
	"context"

	"github.com/ns9ryan/p9_core/rpc/internal/logic/pingservice"
	"github.com/ns9ryan/p9_core/rpc/internal/svc"
	"github.com/ns9ryan/p9_core/rpc/pb/core"
	"github.com/ns9ryan/p9_core/rpc/pb/core/ping"
)

type PingServiceServer struct {
	svcCtx *svc.ServiceContext
	core.UnimplementedPingServiceServer
}

func NewPingServiceServer(svcCtx *svc.ServiceContext) *PingServiceServer {
	return &PingServiceServer{
		svcCtx: svcCtx,
	}
}

// Ping
func (s *PingServiceServer) Ping(ctx context.Context, in *ping.PingRequest) (*ping.PingResponse, error) {
	l := pingservicelogic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
