// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.32.1
// source: p9_core.proto

package core

import (
	base "github.com/ns9ryan/p9_core/rpc/pb/core/base"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_p9_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p9_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_p9_core_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_p9_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_p9_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_p9_core_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_p9_core_proto protoreflect.FileDescriptor

const file_p9_core_proto_rawDesc = "" +
	"\n" +
	"\rp9_core.proto\x12\x04core\x1a\x10types/base.proto\"\r\n" +
	"\vPingRequest\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2<\n" +
	"\vPingService\x12-\n" +
	"\x04Ping\x12\x11.core.PingRequest\x1a\x12.core.PingResponse2T\n" +
	"\vBaseService\x12E\n" +
	"\fInitDatabase\x12\x19.base.InitDatabaseRequest\x1a\x1a.base.InitDatabaseResponseB(Z&github.com/ns9ryan/p9_core/rpc/pb/coreb\x06proto3"

var (
	file_p9_core_proto_rawDescOnce sync.Once
	file_p9_core_proto_rawDescData []byte
)

func file_p9_core_proto_rawDescGZIP() []byte {
	file_p9_core_proto_rawDescOnce.Do(func() {
		file_p9_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_p9_core_proto_rawDesc), len(file_p9_core_proto_rawDesc)))
	})
	return file_p9_core_proto_rawDescData
}

var file_p9_core_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_p9_core_proto_goTypes = []any{
	(*PingRequest)(nil),               // 0: core.PingRequest
	(*PingResponse)(nil),              // 1: core.PingResponse
	(*base.InitDatabaseRequest)(nil),  // 2: base.InitDatabaseRequest
	(*base.InitDatabaseResponse)(nil), // 3: base.InitDatabaseResponse
}
var file_p9_core_proto_depIdxs = []int32{
	0, // 0: core.PingService.Ping:input_type -> core.PingRequest
	2, // 1: core.BaseService.InitDatabase:input_type -> base.InitDatabaseRequest
	1, // 2: core.PingService.Ping:output_type -> core.PingResponse
	3, // 3: core.BaseService.InitDatabase:output_type -> base.InitDatabaseResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_p9_core_proto_init() }
func file_p9_core_proto_init() {
	if File_p9_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_p9_core_proto_rawDesc), len(file_p9_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_p9_core_proto_goTypes,
		DependencyIndexes: file_p9_core_proto_depIdxs,
		MessageInfos:      file_p9_core_proto_msgTypes,
	}.Build()
	File_p9_core_proto = out.File
	file_p9_core_proto_goTypes = nil
	file_p9_core_proto_depIdxs = nil
}
