// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.32.1
// source: p9_core.proto

package core

import (
	base "github.com/ns9ryan/p9_core/rpc/pb/core/base"
	ping "github.com/ns9ryan/p9_core/rpc/pb/core/ping"
	role "github.com/ns9ryan/p9_core/rpc/pb/core/role"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_p9_core_proto protoreflect.FileDescriptor

const file_p9_core_proto_rawDesc = "" +
	"\n" +
	"\rp9_core.proto\x12\x04core\x1a\x10types/ping.proto\x1a\x10types/base.proto\x1a\x10types/role.proto2<\n" +
	"\vPingService\x12-\n" +
	"\x04Ping\x12\x11.ping.PingRequest\x1a\x12.ping.PingResponse2T\n" +
	"\vBaseService\x12E\n" +
	"\fInitDatabase\x12\x19.base.InitDatabaseRequest\x1a\x1a.base.InitDatabaseResponse2\xc2\x02\n" +
	"\vRoleService\x12;\n" +
	"\x06Create\x12\x17.role.CreateRoleRequest\x1a\x18.role.CreateRoleResponse\x12;\n" +
	"\x06Update\x12\x17.role.UpdateRoleRequest\x1a\x18.role.UpdateRoleResponse\x122\n" +
	"\x03Get\x12\x14.role.GetRoleRequest\x1a\x15.role.GetRoleResponse\x127\n" +
	"\x04List\x12\x16.role.ListRolesRequest\x1a\x17.role.ListRolesResponse\x12L\n" +
	"\vBatchDelete\x12\x1d.role.BatchDeleteRolesRequest\x1a\x1e.role.BatchDeleteRolesResponseB(Z&github.com/ns9ryan/p9_core/rpc/pb/coreb\x06proto3"

var file_p9_core_proto_goTypes = []any{
	(*ping.PingRequest)(nil),              // 0: ping.PingRequest
	(*base.InitDatabaseRequest)(nil),      // 1: base.InitDatabaseRequest
	(*role.CreateRoleRequest)(nil),        // 2: role.CreateRoleRequest
	(*role.UpdateRoleRequest)(nil),        // 3: role.UpdateRoleRequest
	(*role.GetRoleRequest)(nil),           // 4: role.GetRoleRequest
	(*role.ListRolesRequest)(nil),         // 5: role.ListRolesRequest
	(*role.BatchDeleteRolesRequest)(nil),  // 6: role.BatchDeleteRolesRequest
	(*ping.PingResponse)(nil),             // 7: ping.PingResponse
	(*base.InitDatabaseResponse)(nil),     // 8: base.InitDatabaseResponse
	(*role.CreateRoleResponse)(nil),       // 9: role.CreateRoleResponse
	(*role.UpdateRoleResponse)(nil),       // 10: role.UpdateRoleResponse
	(*role.GetRoleResponse)(nil),          // 11: role.GetRoleResponse
	(*role.ListRolesResponse)(nil),        // 12: role.ListRolesResponse
	(*role.BatchDeleteRolesResponse)(nil), // 13: role.BatchDeleteRolesResponse
}
var file_p9_core_proto_depIdxs = []int32{
	0,  // 0: core.PingService.Ping:input_type -> ping.PingRequest
	1,  // 1: core.BaseService.InitDatabase:input_type -> base.InitDatabaseRequest
	2,  // 2: core.RoleService.Create:input_type -> role.CreateRoleRequest
	3,  // 3: core.RoleService.Update:input_type -> role.UpdateRoleRequest
	4,  // 4: core.RoleService.Get:input_type -> role.GetRoleRequest
	5,  // 5: core.RoleService.List:input_type -> role.ListRolesRequest
	6,  // 6: core.RoleService.BatchDelete:input_type -> role.BatchDeleteRolesRequest
	7,  // 7: core.PingService.Ping:output_type -> ping.PingResponse
	8,  // 8: core.BaseService.InitDatabase:output_type -> base.InitDatabaseResponse
	9,  // 9: core.RoleService.Create:output_type -> role.CreateRoleResponse
	10, // 10: core.RoleService.Update:output_type -> role.UpdateRoleResponse
	11, // 11: core.RoleService.Get:output_type -> role.GetRoleResponse
	12, // 12: core.RoleService.List:output_type -> role.ListRolesResponse
	13, // 13: core.RoleService.BatchDelete:output_type -> role.BatchDeleteRolesResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_p9_core_proto_init() }
func file_p9_core_proto_init() {
	if File_p9_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_p9_core_proto_rawDesc), len(file_p9_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_p9_core_proto_goTypes,
		DependencyIndexes: file_p9_core_proto_depIdxs,
	}.Build()
	File_p9_core_proto = out.File
	file_p9_core_proto_goTypes = nil
	file_p9_core_proto_depIdxs = nil
}
