// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: p9_core.proto

package server

import (
	"context"

	"github.com/ns9ryan/p9_core/rpc/internal/logic/baseservice"
	"github.com/ns9ryan/p9_core/rpc/internal/svc"
	"github.com/ns9ryan/p9_core/rpc/pb/core"
	"github.com/ns9ryan/p9_core/rpc/pb/core/base"
)

type BaseServiceServer struct {
	svcCtx *svc.ServiceContext
	core.UnimplementedBaseServiceServer
}

func NewBaseServiceServer(svcCtx *svc.ServiceContext) *BaseServiceServer {
	return &BaseServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *BaseServiceServer) InitDatabase(ctx context.Context, in *base.InitDatabaseRequest) (*base.InitDatabaseResponse, error) {
	l := baseservicelogic.NewInitDatabaseLogic(ctx, s.svcCtx)
	return l.InitDatabase(in)
}
