// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: p9_core.proto

package roleservice

import (
	"context"

	"github.com/ns9ryan/p9_core/rpc/pb/core"

	"github.com/ns9ryan/p9_core/rpc/pb/core/role"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	RoleService interface {
		// 创建角色
		Create(ctx context.Context, in *role.CreateRoleRequest, opts ...grpc.CallOption) (*role.CreateRoleResponse, error)
		// 更新角色
		Update(ctx context.Context, in *role.UpdateRoleRequest, opts ...grpc.CallOption) (*role.UpdateRoleResponse, error)
		// 获取角色
		Get(ctx context.Context, in *role.GetRoleRequest, opts ...grpc.CallOption) (*role.GetRoleResponse, error)
		// 获取角色列表
		List(ctx context.Context, in *role.ListRolesRequest, opts ...grpc.CallOption) (*role.ListRolesResponse, error)
		// 批量删除角色
		BatchDelete(ctx context.Context, in *role.BatchDeleteRolesRequest, opts ...grpc.CallOption) (*role.BatchDeleteRolesResponse, error)
	}

	defaultRoleService struct {
		cli zrpc.Client
	}
)

func NewRoleService(cli zrpc.Client) RoleService {
	return &defaultRoleService{
		cli: cli,
	}
}

// 创建角色
func (m *defaultRoleService) Create(ctx context.Context, in *role.CreateRoleRequest, opts ...grpc.CallOption) (*role.CreateRoleResponse, error) {
	client := core.NewRoleServiceClient(m.cli.Conn())
	return client.Create(ctx, in, opts...)
}

// 更新角色
func (m *defaultRoleService) Update(ctx context.Context, in *role.UpdateRoleRequest, opts ...grpc.CallOption) (*role.UpdateRoleResponse, error) {
	client := core.NewRoleServiceClient(m.cli.Conn())
	return client.Update(ctx, in, opts...)
}

// 获取角色
func (m *defaultRoleService) Get(ctx context.Context, in *role.GetRoleRequest, opts ...grpc.CallOption) (*role.GetRoleResponse, error) {
	client := core.NewRoleServiceClient(m.cli.Conn())
	return client.Get(ctx, in, opts...)
}

// 获取角色列表
func (m *defaultRoleService) List(ctx context.Context, in *role.ListRolesRequest, opts ...grpc.CallOption) (*role.ListRolesResponse, error) {
	client := core.NewRoleServiceClient(m.cli.Conn())
	return client.List(ctx, in, opts...)
}

// 批量删除角色
func (m *defaultRoleService) BatchDelete(ctx context.Context, in *role.BatchDeleteRolesRequest, opts ...grpc.CallOption) (*role.BatchDeleteRolesResponse, error) {
	client := core.NewRoleServiceClient(m.cli.Conn())
	return client.BatchDelete(ctx, in, opts...)
}
