// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: p9_core.proto

package pingservice

import (
	"context"

	"github.com/ns9ryan/p9_core/rpc/pb/core"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	PingRequest  = core.PingRequest
	PingResponse = core.PingResponse

	PingService interface {
		Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	}

	defaultPingService struct {
		cli zrpc.Client
	}
)

func NewPingService(cli zrpc.Client) PingService {
	return &defaultPingService{
		cli: cli,
	}
}

func (m *defaultPingService) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	client := core.NewPingServiceClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
