// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.32.1
// source: types/base.proto

package base

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitDatabaseRequest) Reset() {
	*x = InitDatabaseRequest{}
	mi := &file_types_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitDatabaseRequest) ProtoMessage() {}

func (x *InitDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitDatabaseRequest.ProtoReflect.Descriptor instead.
func (*InitDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_types_base_proto_rawDescGZIP(), []int{0}
}

type InitDatabaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitDatabaseResponse) Reset() {
	*x = InitDatabaseResponse{}
	mi := &file_types_base_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitDatabaseResponse) ProtoMessage() {}

func (x *InitDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_base_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitDatabaseResponse.ProtoReflect.Descriptor instead.
func (*InitDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_types_base_proto_rawDescGZIP(), []int{1}
}

var File_types_base_proto protoreflect.FileDescriptor

const file_types_base_proto_rawDesc = "" +
	"\n" +
	"\x10types/base.proto\x12\x04base\"\x15\n" +
	"\x13InitDatabaseRequest\"\x16\n" +
	"\x14InitDatabaseResponseB-Z+github.com/ns9ryan/p9_core/rpc/pb/core/baseb\x06proto3"

var (
	file_types_base_proto_rawDescOnce sync.Once
	file_types_base_proto_rawDescData []byte
)

func file_types_base_proto_rawDescGZIP() []byte {
	file_types_base_proto_rawDescOnce.Do(func() {
		file_types_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_base_proto_rawDesc), len(file_types_base_proto_rawDesc)))
	})
	return file_types_base_proto_rawDescData
}

var file_types_base_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_types_base_proto_goTypes = []any{
	(*InitDatabaseRequest)(nil),  // 0: base.InitDatabaseRequest
	(*InitDatabaseResponse)(nil), // 1: base.InitDatabaseResponse
}
var file_types_base_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_types_base_proto_init() }
func file_types_base_proto_init() {
	if File_types_base_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_base_proto_rawDesc), len(file_types_base_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_base_proto_goTypes,
		DependencyIndexes: file_types_base_proto_depIdxs,
		MessageInfos:      file_types_base_proto_msgTypes,
	}.Build()
	File_types_base_proto = out.File
	file_types_base_proto_goTypes = nil
	file_types_base_proto_depIdxs = nil
}
